version: '2'
services:
  plataforma_backoffice-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/plataforma_backoffice/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=plataforma_backoffice
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
